import { THUMB_KEY } from '../shapes/geometry.ts';
import { faceFromEntries, fromFaces, groupNamedModifierKeyMeanings, withAliases, type Face, type Layout } from './types.ts';

/**
 * かわせみ配列+。
 *
 * 出典:
 *   semialt/kawasemi `master` ブランチ
 *   `Kikyo/かわせみ配列+.kky`
 *   最後の変更コミット: 911bb8f
 *   blob: 220851f9e4d733c1c7cf83000f750faed02e6525
 *
 * 出力の表現はKikyo版から次のように正規化している。
 * `，→、`、`．→。`、`－→ー`、`va/vi/vu/ve/vo→ヴァ/ヴィ/ヴ/ヴェ/ヴォ`。
 *
 * KikyoはJIS物理配列なので、ANSIに存在しない各段末尾の専用キーは除外する。
 * 数字・英数記号・括弧マクロ・！・？など解析対象外の出力も除外し、かな・長音・日本語句読点を移植する。
 *
 * 同じ出力に複数の打ち方が定義されている場合、keydistのLayoutは代替Sequenceを持てないため、
 * 同時押しの押下キー数が最少の定義を採る。同数ならKikyoファイルで先に現れる定義を採る。
 */
/**
 * compositionの面の帰属先。文字キー1つを押しながら別の文字キーで打つ面のうち、
 * 左手の行指定キーの面は層に数える。右手1キーの二重母音拡張の面、左手コンボ拡張、
 * triggerが2キー以上の面は、コンボ枠に数える。
 */
const LAYER_COMPOSITION = {
  inputRole: 'composition',
  compositionAggregation: 'layer',
  triggerPersistence: 'single',
} as const;
const COMBO_COMPOSITION = {
  inputRole: 'composition',
  compositionAggregation: 'combo',
  triggerPersistence: 'single',
} as const;

/** 行指定キーの面。画面に出す層の名前は、作者の資料（Kikyo定義の各面の呼び名）に合わせる。 */
const layerComposition = (presentationLabel: string) => ({ ...LAYER_COMPOSITION, presentationLabel });

type SourceFace = {
  trigger: readonly string[];
  entries: Readonly<Record<string, string>>;
  options?: Pick<Face, 'layer' | 'inputRole' | 'compositionAggregation' | 'triggerPersistence' | 'presentationLabel'>;
};

function sourceFace(
  trigger: readonly string[],
  entries: Readonly<Record<string, string>>,
  options?: SourceFace['options'],
): SourceFace {
  return { trigger, entries, options };
}

function selectShortestFaces(sources: readonly SourceFace[]): Face[] {
  type Winner = { faceIndex: number; key: string; presses: number };
  const winners = new Map<string, Winner>();

  for (const [faceIndex, source] of sources.entries()) {
    for (const [key, output] of Object.entries(source.entries)) {
      const presses = new Set([...source.trigger, key]).size;
      const current = winners.get(output);
      if (current === undefined || presses < current.presses) {
        winners.set(output, { faceIndex, key, presses });
      }
    }
  }

  const faces: Face[] = [];
  for (const [faceIndex, source] of sources.entries()) {
    const entries = Object.fromEntries(
      Object.entries(source.entries).filter(([key, output]) => {
        const winner = winners.get(output);
        return winner?.faceIndex === faceIndex && winner.key === key;
      }),
    );
    if (Object.keys(entries).length === 0) continue;

    faces.push({
      ...faceFromEntries(source.trigger, 'simultaneous', entries),
      ...source.options,
    });
  }
  return faces;
}

const KAWASEMI_PLUS_SOURCES: SourceFace[] = [
  sourceFace([], {
      "q": "に",
      "w": "が",
      "e": "じ",
      "r": "で",
      "t": "ば",
      "y": "れ",
      "u": "よ",
      "i": "ゆ",
      "o": "や",
      "p": "を",
      "a": "の",
      "s": "か",
      "d": "し",
      "f": "と",
      "g": "は",
      "h": "え",
      "j": "お",
      "k": "う",
      "l": "い",
      ";": "あ",
      "z": "な",
      "x": "る",
      "c": "ま",
      "v": "て",
      "b": "わ",
      "n": "っ",
      "m": "ん",
      ",": "、",
      ".": "。",
      "/": "ー",
    }, { inputRole: 'layer' }),
  sourceFace(["a"], {
      "u": "にょ",
      "i": "にゅ",
      "o": "にゃ",
      "h": "ね",
      "j": "の",
      "k": "ぬ",
      "l": "に",
      ";": "な",
      "n": "ねん",
      "m": "のん",
      ",": "ぬん",
      ".": "にん",
      "/": "なん",
    }, layerComposition('な行')),
  sourceFace(["s"], {
      "7": "くぉ",
      "-": "くぃ",
      "y": "くぇ",
      "u": "きょ",
      "i": "きゅ",
      "o": "きゃ",
      "p": "くぁ",
      "h": "け",
      "j": "こ",
      "k": "く",
      "l": "き",
      ";": "か",
      "n": "けん",
      "m": "こん",
      ",": "くん",
      ".": "きん",
      "/": "かん",
    }, layerComposition('か行')),
  sourceFace(["d"], {
      "-": "すぃ",
      "y": "しぇ",
      "u": "しょ",
      "i": "しゅ",
      "o": "しゃ",
      "h": "せ",
      "j": "そ",
      "k": "す",
      "l": "し",
      ";": "さ",
      "n": "せん",
      "m": "そん",
      ",": "すん",
      ".": "しん",
      "/": "さん",
    }, layerComposition('さ行')),
  sourceFace(["d"], {
      "s": "こと",
      "f": "する",
    }, COMBO_COMPOSITION),
  sourceFace(["f"], {
      "6": "つぇ",
      "7": "つぉ",
      "8": "とぅ",
      "9": "てぃ",
      "y": "ちぇ",
      "u": "ちょ",
      "i": "ちゅ",
      "o": "ちゃ",
      "p": "つぁ",
      "h": "て",
      "j": "と",
      "k": "つ",
      "l": "ち",
      ";": "た",
      "n": "てん",
      "m": "とん",
      ",": "つん",
      ".": "ちん",
      "/": "たん",
    }, layerComposition('た行')),
  sourceFace(["f"], {
      "g": "ひと",
    }, COMBO_COMPOSITION),
  sourceFace(["g"], {
      "7": "ふぉ",
      "8": "ふゅ",
      "9": "ふぃ",
      "y": "ふぇ",
      "u": "ひょ",
      "i": "ひゅ",
      "o": "ひゃ",
      "p": "ふぁ",
      "h": "へ",
      "j": "ほ",
      "k": "ふ",
      "l": "ひ",
      ";": "は",
      "n": "へん",
      "m": "ほん",
      ",": "ふん",
      ".": "ひん",
      "/": "はん",
    }, layerComposition('は行')),
  sourceFace(["z"], {
      "/": "なん",
    }, layerComposition('な行の補完')),
  sourceFace(["x"], {
      "u": "りょ",
      "i": "りゅ",
      "o": "りゃ",
      "h": "れ",
      "j": "ろ",
      "k": "る",
      "l": "り",
      ";": "ら",
      "n": "れん",
      "m": "ろん",
      ",": "るん",
      ".": "りん",
      "/": "らん",
    }, layerComposition('ら行')),
  sourceFace(["x"], {
      "z": "もの",
    }, COMBO_COMPOSITION),
  sourceFace(["c"], {
      "u": "みょ",
      "i": "みゅ",
      "o": "みゃ",
      "h": "め",
      "j": "も",
      "k": "む",
      "l": "み",
      ";": "ま",
      "n": "めん",
      "m": "もん",
      ",": "むん",
      ".": "みん",
      "/": "まん",
    }, layerComposition('ま行')),
  sourceFace(["c"], {
      "x": "から",
      "v": "ます",
    }, COMBO_COMPOSITION),
  sourceFace(["v"], {
      "j": "・",
      "k": "…",
      ",": "、",
    }, layerComposition('記号')),
  sourceFace(["b"], {
      "u": "ぴょ",
      "i": "ぴゅ",
      "o": "ぴゃ",
      "h": "ぺ",
      "j": "ぽ",
      "k": "ぷ",
      "l": "ぴ",
      ";": "ぱ",
      "n": "ぺん",
      "m": "ぽん",
      ",": "ぷん",
      ".": "ぴん",
      "/": "ぱん",
    }, layerComposition('ぱ行')),
  sourceFace(["q"], {
      "9": "ゐ",
      "y": "ヶ",
      "u": "ょ",
      "i": "ゅ",
      "o": "ゃ",
      "p": "ゎ",
      "h": "ぇ",
      "j": "ぉ",
      "k": "ぅ",
      "l": "ぃ",
      ";": "ぁ",
      "n": "ゑ",
      ",": "、",
      ".": "。",
      "/": "ヵ",
    }, layerComposition('捨て仮名、旧かな')),
  sourceFace(["w"], {
      "0": "ぐゎ",
      "7": "ぐぉ",
      "9": "ぐぃ",
      "y": "ぐぇ",
      "u": "ぎょ",
      "i": "ぎゅ",
      "o": "ぎゃ",
      "[": "ぐぁ",
      "h": "げ",
      "j": "ご",
      "k": "ぐ",
      "l": "ぎ",
      ";": "が",
      "n": "げん",
      "m": "ごん",
      ",": "ぐん",
      ".": "ぎん",
      "/": "がん",
    }, layerComposition('が行')),
  sourceFace(["e"], {
      "9": "ずぃ",
      "y": "じぇ",
      "u": "じょ",
      "i": "じゅ",
      "o": "じゃ",
      "h": "ぜ",
      "j": "ぞ",
      "k": "ず",
      "l": "じ",
      ";": "ざ",
      "n": "ぜん",
      "m": "ぞん",
      ",": "ずん",
      ".": "じん",
      "/": "ざん",
    }, layerComposition('ざ行')),
  sourceFace(["r"], {
      "8": "どぅ",
      "9": "でぃ",
      "y": "ぢぇ",
      "u": "ぢょ",
      "i": "でゅ",
      "o": "ぢゃ",
      "h": "で",
      "j": "ど",
      "k": "づ",
      "l": "ぢ",
      ";": "だ",
      "n": "でん",
      "m": "どん",
      ",": "づん",
      ".": "ぢん",
      "/": "だん",
    }, layerComposition('だ行')),
  sourceFace(["r"], {
      "e": "です",
    }, COMBO_COMPOSITION),
  sourceFace(["t"], {
      "7": "ヴォ",
      "8": "ヴ",
      "9": "ヴィ",
      "y": "ヴェ",
      "u": "びょ",
      "i": "びゅ",
      "o": "びゃ",
      "p": "ヴァ",
      "h": "べ",
      "j": "ぼ",
      "k": "ぶ",
      "l": "び",
      ";": "ば",
      "n": "べん",
      "m": "ぼん",
      ",": "ぶん",
      ".": "びん",
      "/": "ばん",
    }, layerComposition('ば行')),
  sourceFace(["l", ";"], {
      "w": "がい",
      "e": "ざい",
      "r": "だい",
      "t": "ばい",
      "a": "ない",
      "s": "かい",
      "d": "さい",
      "f": "たい",
      "g": "はい",
      "x": "らい",
      "c": "まい",
      "b": "ぱい",
    }, COMBO_COMPOSITION),
  sourceFace(["l"], {
      "k": "うう",
      ";": "あい",
    }, COMBO_COMPOSITION),
  sourceFace(["k", "l"], {
      "w": "ぐう",
      "e": "ずう",
      "r": "づう",
      "t": "ぶう",
      "a": "ぬう",
      "s": "くう",
      "d": "すう",
      "f": "つう",
      "g": "ふう",
      "x": "るう",
      "c": "むう",
      "b": "ぷう",
    }, COMBO_COMPOSITION),
  sourceFace(["j", "k"], {
      "w": "ごう",
      "e": "ぞう",
      "r": "どう",
      "t": "ぼう",
      "a": "のう",
      "s": "こう",
      "d": "そう",
      "f": "とう",
      "g": "ほう",
      "x": "ろう",
      "c": "もう",
      "b": "ぽう",
    }, COMBO_COMPOSITION),
  sourceFace(["j"], {
      "h": "えい",
      "k": "おう",
    }, COMBO_COMPOSITION),
  sourceFace(["h", "j"], {
      "w": "げい",
      "e": "ぜい",
      "r": "でい",
      "t": "べい",
      "a": "ねい",
      "s": "けい",
      "d": "せい",
      "f": "てい",
      "g": "へい",
      "x": "れい",
      "c": "めい",
      "b": "ぺい",
    }, COMBO_COMPOSITION),
  sourceFace([".", "/"], {
      "w": "ぎい",
      "e": "じい",
      "r": "ぢい",
      "t": "びい",
      "a": "にい",
      "s": "きい",
      "d": "しい",
      "f": "ちい",
      "g": "ひい",
      "x": "りい",
      "c": "みい",
      "b": "ぴい",
    }, COMBO_COMPOSITION),
  sourceFace([",", "."], {
      "w": "ぐい",
      "e": "ずい",
      "r": "づい",
      "t": "ぶい",
      "a": "ぬい",
      "s": "くい",
      "d": "すい",
      "f": "つい",
      "g": "ふい",
      "x": "るい",
      "c": "むい",
      "b": "ぷい",
    }, COMBO_COMPOSITION),
  sourceFace(["."], {
      ",": "うい",
      "/": "いい",
    }, COMBO_COMPOSITION),
  sourceFace(["o"], {
      "i": "ゆう",
      "p": "やい",
    }, COMBO_COMPOSITION),
  sourceFace(["i", "o"], {
      "w": "ぎゅう",
      "e": "じゅう",
      "r": "でゅう",
      "t": "びゅう",
      "a": "にゅう",
      "s": "きゅう",
      "d": "しゅう",
      "f": "ちゅう",
      "g": "ひゅう",
      "x": "りゅう",
      "c": "みゅう",
      "b": "ぴゅう",
    }, COMBO_COMPOSITION),
  sourceFace(["u", "i"], {
      "w": "ぎょう",
      "e": "じょう",
      "r": "ぢょう",
      "t": "びょう",
      "a": "にょう",
      "s": "きょう",
      "d": "しょう",
      "f": "ちょう",
      "g": "ひょう",
      "x": "りょう",
      "c": "みょう",
      "b": "ぴょう",
    }, COMBO_COMPOSITION),
  sourceFace(["i"], {
      "u": "よう",
    }, COMBO_COMPOSITION),
  sourceFace(["o", "p"], {
      "w": "ぎゃい",
      "e": "じゃい",
      "r": "ぢゃい",
      "t": "ゔぁい",
      "a": "にゃい",
      "s": "きゃい",
      "d": "しゃい",
      "f": "ちゃい",
      "g": "ふぁい",
      "x": "りゃい",
      "c": "みゃい",
      "b": "ぴゃい",
    }, COMBO_COMPOSITION),
  sourceFace(["y", "u"], {
      "w": "ぐぇい",
      "e": "じぇい",
      "r": "ぢぇい",
      "t": "ヴぇい",
      "s": "くぇい",
      "d": "しぇい",
      "f": "ちぇい",
      "g": "ふぇい",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT], {
      "q": "にく",
      "w": "がく",
      "e": "じく",
      "r": "どく",
      "t": "ばく",
      "y": "れき",
      "u": "よく",
      "i": "ゆく",
      "o": "やく",
      "a": "のき",
      "s": "かく",
      "d": "しき",
      "f": "とく",
      "g": "はく",
      "h": "えく",
      "j": "おく",
      "k": "うく",
      "l": "いく",
      ";": "あく",
      "z": "なく",
      "x": "らく",
      "c": "まく",
      "v": "てき",
      "b": "わく",
      "n": "えき",
      "m": "おき",
      ",": "うき",
      ".": "いき",
      "/": "あき",
    }, { layer: "右親指", inputRole: 'modifier', triggerPersistence: 'hold-capable' }),
  sourceFace([THUMB_KEY.RT, "a"], {
      "u": "にょく",
      "i": "にゅく",
      "o": "にゃく",
      "h": "ねく",
      "j": "のく",
      "k": "ぬく",
      "l": "にく",
      ";": "なく",
      "n": "ねき",
      "m": "のき",
      ",": "ぬき",
      ".": "にき",
      "/": "なき",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "s"], {
      "u": "きょく",
      "i": "きゅく",
      "o": "きゃく",
      "h": "けく",
      "j": "こく",
      "k": "くく",
      "l": "きく",
      ";": "かく",
      "n": "けき",
      "m": "こき",
      ",": "くき",
      ".": "きき",
      "/": "かき",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "d"], {
      "-": "すぃ",
      "y": "しぇ",
      "u": "しょく",
      "i": "しゅく",
      "o": "しゃく",
      "h": "せく",
      "j": "そく",
      "k": "すく",
      "l": "しく",
      ";": "さく",
      "n": "せき",
      "m": "そき",
      ",": "すき",
      ".": "しき",
      "/": "さき",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "f"], {
      "6": "つぇ",
      "7": "つぉ",
      "8": "とぅ",
      "9": "てぃ",
      "y": "ちぇ",
      "u": "ちょく",
      "i": "ちゅく",
      "o": "ちゃく",
      "p": "つぁ",
      "h": "てく",
      "j": "とく",
      "k": "つく",
      "l": "ちく",
      ";": "たく",
      "n": "てき",
      "m": "とき",
      ",": "つき",
      ".": "ちき",
      "/": "たき",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "g"], {
      "7": "ふぉ",
      "8": "ふゅく",
      "9": "ふぃ",
      "y": "ふぇ",
      "u": "ひょく",
      "i": "ひゅく",
      "o": "ひゃく",
      "p": "ふぁ",
      "h": "へく",
      "j": "ほく",
      "k": "ふく",
      "l": "ひく",
      ";": "はく",
      "n": "へき",
      "m": "ほき",
      ",": "ふき",
      ".": "ひき",
      "/": "はき",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "x"], {
      "u": "りょく",
      "i": "りゅく",
      "o": "りゃく",
      "h": "れく",
      "j": "ろく",
      "k": "るく",
      "l": "りく",
      ";": "らく",
      "n": "れき",
      "m": "ろき",
      ",": "るき",
      ".": "りき",
      "/": "らき",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "c"], {
      "u": "みょく",
      "i": "みゅく",
      "o": "みゃく",
      "h": "めく",
      "j": "もく",
      "k": "むく",
      "l": "みく",
      ";": "まく",
      "n": "めき",
      "m": "もき",
      ",": "むき",
      ".": "みき",
      "/": "まき",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "v"], {
      "j": "・",
      "k": "…",
      ",": "、",
      ".": "。",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "b"], {
      "u": "ぴょく",
      "i": "ぴゅく",
      "o": "ぴゃく",
      "h": "ぺく",
      "j": "ぽく",
      "k": "ぷく",
      "l": "ぴく",
      ";": "ぱく",
      "n": "ぺき",
      "m": "ぽき",
      ",": "ぷき",
      ".": "ぴき",
      "/": "ぱき",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "q"], {
      "9": "ゐ",
      "y": "ヶ",
      "u": "ょく",
      "i": "ゅく",
      "o": "ゃく",
      "p": "ゎ",
      "h": "ぇ",
      "j": "ぉ",
      "k": "ぅ",
      "l": "ぃ",
      ";": "ぁ",
      "n": "ゑ",
      ",": "、",
      ".": "。",
      "/": "ヵ",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "w"], {
      "0": "ぐゎ",
      "7": "ぐぉ",
      "9": "ぐぃ",
      "y": "ぐぇ",
      "u": "ぎょく",
      "i": "ぎゅく",
      "o": "ぎゃく",
      "[": "ぐぁ",
      "h": "げく",
      "j": "ごく",
      "k": "ぐく",
      "l": "ぎく",
      ";": "がく",
      "n": "げき",
      "m": "ごき",
      ",": "ぐき",
      ".": "ぎき",
      "/": "がき",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "e"], {
      "9": "ずぃ",
      "y": "じぇ",
      "u": "じょく",
      "i": "じゅく",
      "o": "じゃく",
      "h": "ぜく",
      "j": "ぞく",
      "k": "ずく",
      "l": "じく",
      ";": "ざく",
      "n": "ぜき",
      "m": "ぞき",
      ",": "ずき",
      ".": "じき",
      "/": "ざき",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "r"], {
      "8": "どぅ",
      "9": "でぃ",
      "y": "ぢぇ",
      "u": "ぢょく",
      "i": "でゅく",
      "o": "ぢゃく",
      "h": "でく",
      "j": "どく",
      "k": "づく",
      "l": "ぢく",
      ";": "だく",
      "n": "でき",
      "m": "どき",
      ",": "づき",
      ".": "ぢき",
      "/": "だき",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.RT, "t"], {
      "7": "ヴォ",
      "8": "ヴ",
      "9": "ヴィ",
      "y": "ヴェ",
      "u": "びょく",
      "i": "びゅく",
      "o": "びゃく",
      "p": "ヴァ",
      "h": "べく",
      "j": "ぼく",
      "k": "ぶく",
      "l": "びく",
      ";": "ばく",
      "n": "べき",
      "m": "ぼき",
      ",": "ぶき",
      ".": "びき",
      "/": "ばき",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT], {
      "q": "にち",
      "w": "がつ",
      "e": "じつ",
      "r": "げつ",
      "t": "べつ",
      "y": "れつ",
      "u": "よつ",
      "i": "ゆつ",
      "o": "やつ",
      "p": "を",
      "a": "のち",
      "s": "かつ",
      "d": "しつ",
      "f": "とつ",
      "g": "はつ",
      "h": "えつ",
      "j": "おつ",
      "k": "うつ",
      "l": "いつ",
      ";": "あつ",
      "z": "なつ",
      "x": "りつ",
      "c": "まつ",
      "v": "てつ",
      "b": "ぱつ",
      "n": "えち",
      "m": "おち",
      ",": "うち",
      ".": "いち",
    }, { layer: "左親指", inputRole: 'modifier', triggerPersistence: 'hold-capable' }),
  sourceFace([THUMB_KEY.LT, "a"], {
      "u": "にょ",
      "i": "にゅ",
      "o": "にゃ",
      "h": "ねつ",
      "j": "のつ",
      "k": "ぬつ",
      "l": "につ",
      ";": "なつ",
      "n": "ねち",
      "m": "のち",
      ",": "ぬち",
      ".": "にち",
      "/": "なち",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "s"], {
      "7": "くぉ",
      "-": "くぃ",
      "y": "くぇ",
      "u": "きょ",
      "i": "きゅ",
      "o": "きゃ",
      "p": "くぁ",
      "h": "けつ",
      "j": "こつ",
      "k": "くつ",
      "l": "きつ",
      ";": "かつ",
      "n": "けち",
      "m": "こち",
      ",": "くち",
      ".": "きち",
      "/": "かち",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "d"], {
      "-": "すぃ",
      "y": "しぇ",
      "u": "しょ",
      "i": "しゅつ",
      "o": "しゃ",
      "h": "せつ",
      "j": "そつ",
      "k": "すつ",
      "l": "しつ",
      ";": "さつ",
      "n": "せち",
      "m": "そち",
      ",": "すち",
      ".": "しち",
      "/": "さち",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "f"], {
      "6": "つぇ",
      "7": "つぉ",
      "8": "とぅ",
      "9": "てぃ",
      "y": "ちぇ",
      "u": "ちょ",
      "i": "ちゅ",
      "o": "ちゃ",
      "p": "つぁ",
      "h": "てつ",
      "j": "とつ",
      "k": "つつ",
      "l": "ちつ",
      ";": "たつ",
      "n": "てち",
      "m": "とち",
      ",": "つち",
      ".": "ちち",
      "/": "たち",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "g"], {
      "7": "ふぉ",
      "8": "ふゅ",
      "9": "ふぃ",
      "y": "ふぇ",
      "u": "ひょ",
      "i": "ひゅ",
      "o": "ひゃ",
      "p": "ふぁ",
      "h": "へつ",
      "j": "ほつ",
      "k": "ふつ",
      "l": "ひつ",
      ";": "はつ",
      "n": "へち",
      "m": "ほち",
      ",": "ふち",
      ".": "ひち",
      "/": "はち",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "x"], {
      "u": "りょ",
      "i": "りゅ",
      "o": "りゃ",
      "h": "れつ",
      "j": "ろつ",
      "k": "るつ",
      "l": "りつ",
      ";": "らつ",
      "n": "れち",
      "m": "ろち",
      ",": "るち",
      ".": "りち",
      "/": "らち",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "c"], {
      "u": "みょ",
      "i": "みゅ",
      "o": "みゃ",
      "h": "めつ",
      "j": "もつ",
      "k": "むつ",
      "l": "みつ",
      ";": "まつ",
      "n": "めち",
      "m": "もち",
      ",": "むち",
      ".": "みち",
      "/": "まち",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "v"], {
      "j": "・",
      "k": "…",
      ",": "、",
      ".": "。",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "b"], {
      "u": "ぴょ",
      "i": "ぴゅ",
      "o": "ぴゃ",
      "h": "ぺつ",
      "j": "ぽつ",
      "k": "ぷつ",
      "l": "ぴつ",
      ";": "ぱつ",
      "n": "ぺち",
      "m": "ぽち",
      ",": "ぷち",
      ".": "ぴち",
      "/": "ぱち",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "q"], {
      "9": "ゐ",
      "y": "ヶ",
      "u": "ょ",
      "i": "ゅ",
      "o": "ゃ",
      "p": "ゎ",
      "h": "ぇ",
      "j": "ぉ",
      "k": "ぅ",
      "l": "ぃ",
      ";": "ぁ",
      "n": "ゑ",
      ",": "、",
      ".": "。",
      "/": "ヵ",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "w"], {
      "0": "ぐゎ",
      "7": "ぐぉ",
      "9": "ぐぃ",
      "y": "ぐぇ",
      "u": "ぎょ",
      "i": "ぎゅ",
      "o": "ぎゃ",
      "[": "ぐぁ",
      "h": "げつ",
      "j": "ごつ",
      "k": "ぐつ",
      "l": "ぎつ",
      ";": "がつ",
      "n": "げち",
      "m": "ごち",
      ",": "ぐち",
      ".": "ぎち",
      "/": "がち",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "e"], {
      "9": "ずぃ",
      "y": "じぇ",
      "u": "じょ",
      "i": "じゅつ",
      "o": "じゃ",
      "h": "ぜつ",
      "j": "ぞつ",
      "k": "ずつ",
      "l": "じつ",
      ";": "ざつ",
      "n": "ぜち",
      "m": "ぞち",
      ",": "ずち",
      ".": "じち",
      "/": "ざち",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "r"], {
      "8": "どぅ",
      "9": "でぃ",
      "y": "ぢぇ",
      "u": "ぢょ",
      "i": "でゅ",
      "o": "ぢゃ",
      "h": "でつ",
      "j": "どつ",
      "k": "づつ",
      "l": "ぢつ",
      ";": "だつ",
      "n": "でち",
      "m": "どち",
      ",": "づち",
      ".": "ぢち",
      "/": "だち",
    }, COMBO_COMPOSITION),
  sourceFace([THUMB_KEY.LT, "t"], {
      "7": "ヴォ",
      "8": "ヴ",
      "9": "ヴィ",
      "y": "ヴェ",
      "u": "びょ",
      "i": "びゅ",
      "o": "びゃ",
      "p": "ヴァ",
      "h": "べつ",
      "j": "ぼつ",
      "k": "ぶつ",
      "l": "びつ",
      ";": "ばつ",
      "n": "べち",
      "m": "ぼち",
      ",": "ぶち",
      ".": "びち",
      "/": "ばち",
    }, COMBO_COMPOSITION),
];

/**
 * 行指定キーは位置で決まるキーで、単打面の文字の意味を持たない。
 * 層の名前と同じ修飾のキーとして、物理キーの名前で出す。
 * コンボ枠に計上する面は行指定の働きをしないので、意味を書かない。
 */
const withLineKeyMeaning = (face: Face): Face =>
  face.compositionAggregation === 'layer' && face.presentationLabel !== undefined
    ? {
      ...face,
      triggerMeaningGroups: Object.fromEntries(face.trigger.map((key) => [key, face.presentationLabel!])),
    }
    : face;

export const KAWASEMI_PLUS_FACES: Face[] = selectShortestFaces(KAWASEMI_PLUS_SOURCES).map(withLineKeyMeaning);

const layout: Layout = {
  ...fromFaces('kawasemi-plus', 'かわせみ配列+', KAWASEMI_PLUS_FACES),
  triggerMeanings: groupNamedModifierKeyMeanings(KAWASEMI_PLUS_FACES),
};
layout.legends.set(THUMB_KEY.LT, '左親指');
layout.legends.set(THUMB_KEY.RT, '右親指');

export const KAWASEMI_PLUS = withAliases(layout, ['かわせみ', 'かわせみぷらす']);
