import { faceFromEntries, fromFaces, type Face, type Layout } from './types.ts';

/**
 * かわせみ配列改。
 *
 * 正本:
 *   semialt/kawasemi `plus` branch
 *   `Win_DvorakJ/かわせみ配列改.txt`
 *   source blob: 0652e3633be75bdc10bf180eb3e1183a29e89904
 *
 * 通常版との差分は二重母音拡張のみ。かわせみ配列+にある
 * くき・つち・左手コンボ拡張は含めない。
 *
 * DvorakJ定義の単打面には長音記号「ー」が数字段とQWERTYの / 位置の2か所にあるが、
 * keydistでは数字段側を除外し、QWERTY / 位置の「ー」を採用する。
 * 数字・英数記号・括弧マクロなど解析対象外の出力も除外し、かな・日本語句読点を移植する。
 */
type SourceFace = {
  trigger: readonly string[];
  entries: Readonly<Record<string, string>>;
  options?: Pick<Face, 'layer' | 'inputRole' | 'triggerPersistence'>;
};

function sourceFace(
  trigger: readonly string[],
  entries: Readonly<Record<string, string>>,
  options?: SourceFace['options'],
): SourceFace {
  return { trigger, entries, options };
}

function selectShortestFaces(sources: readonly SourceFace[]): Face[] {
  type Winner = { faceIndex: number; key: string; presses: number };
  const winners = new Map<string, Winner>();

  for (const [faceIndex, source] of sources.entries()) {
    for (const [key, output] of Object.entries(source.entries)) {
      const presses = new Set([...source.trigger, key]).size;
      const current = winners.get(output);
      if (current === undefined || presses < current.presses) {
        winners.set(output, { faceIndex, key, presses });
      }
    }
  }

  const faces: Face[] = [];
  for (const [faceIndex, source] of sources.entries()) {
    const entries = Object.fromEntries(
      Object.entries(source.entries).filter(([key, output]) => {
        const winner = winners.get(output);
        return winner?.faceIndex === faceIndex && winner.key === key;
      }),
    );
    if (Object.keys(entries).length === 0) continue;

    faces.push({
      ...faceFromEntries(source.trigger, 'simultaneous', entries),
      ...source.options,
    });
  }
  return faces;
}

const KAWASEMI_KAI_SOURCES: SourceFace[] = [
  sourceFace([], {
      "q": "に",
      "w": "が",
      "e": "じ",
      "r": "で",
      "t": "ば",
      "y": "れ",
      "u": "よ",
      "i": "ゆ",
      "o": "や",
      "p": "を",
      "a": "の",
      "s": "か",
      "d": "し",
      "f": "と",
      "g": "は",
      "h": "え",
      "j": "お",
      "k": "う",
      "l": "い",
      ";": "あ",
      "z": "な",
      "x": "る",
      "c": "ま",
      "v": "て",
      "b": "わ",
      "n": "っ",
      "m": "ん",
      ",": "、",
      ".": "。",
      "/": "ー",
    }, { inputRole: 'layer' }),
  sourceFace(["a"], {
      "u": "にょ",
      "i": "にゅ",
      "o": "にゃ",
      "h": "ね",
      "j": "の",
      "k": "ぬ",
      "l": "に",
      ";": "な",
      "n": "ねん",
      "m": "のん",
      ",": "ぬん",
      ".": "にん",
      "/": "なん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["s"], {
      "7": "くぉ",
      "-": "くぃ",
      "y": "くぇ",
      "u": "きょ",
      "i": "きゅ",
      "o": "きゃ",
      "p": "くぁ",
      "h": "け",
      "j": "こ",
      "k": "く",
      "l": "き",
      ";": "か",
      "n": "けん",
      "m": "こん",
      ",": "くん",
      ".": "きん",
      "/": "かん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["d"], {
      "-": "すぃ",
      "y": "しぇ",
      "u": "しょ",
      "i": "しゅ",
      "o": "しゃ",
      "s": "こと",
      "f": "する",
      "h": "せ",
      "j": "そ",
      "k": "す",
      "l": "し",
      ";": "さ",
      "n": "せん",
      "m": "そん",
      ",": "すん",
      ".": "しん",
      "/": "さん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["f"], {
      "6": "つぇ",
      "7": "つぉ",
      "8": "とぅ",
      "9": "てぃ",
      "y": "ちぇ",
      "u": "ちょ",
      "i": "ちゅ",
      "o": "ちゃ",
      "p": "つぁ",
      "g": "ため",
      "h": "て",
      "j": "と",
      "k": "つ",
      "l": "ち",
      ";": "た",
      "n": "てん",
      "m": "とん",
      ",": "つん",
      ".": "ちん",
      "/": "たん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["g"], {
      "7": "ふぉ",
      "8": "ふゅ",
      "9": "ふぃ",
      "y": "ふぇ",
      "u": "ひょ",
      "i": "ひゅ",
      "o": "ひゃ",
      "p": "ふぁ",
      "h": "へ",
      "j": "ほ",
      "k": "ふ",
      "l": "ひ",
      ";": "は",
      "n": "へん",
      "m": "ほん",
      ",": "ふん",
      ".": "ひん",
      "/": "はん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["z"], {
      "/": "なん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["x"], {
      "u": "りょ",
      "i": "りゅ",
      "o": "りゃ",
      "h": "れ",
      "j": "ろ",
      "k": "る",
      "l": "り",
      ";": "ら",
      "n": "れん",
      "m": "ろん",
      ",": "るん",
      ".": "りん",
      "/": "らん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["c"], {
      "u": "みょ",
      "i": "みゅ",
      "o": "みゃ",
      "h": "め",
      "j": "も",
      "k": "む",
      "l": "み",
      ";": "ま",
      "x": "から",
      "v": "ます",
      "n": "めん",
      "m": "もん",
      ",": "むん",
      ".": "みん",
      "/": "まん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["v"], {
      "j": "・",
      "k": "…",
      ",": "、",
      ".": "。",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["b"], {
      "u": "ぴょ",
      "i": "ぴゅ",
      "o": "ぴゃ",
      "h": "ぺ",
      "j": "ぽ",
      "k": "ぷ",
      "l": "ぴ",
      ";": "ぱ",
      "n": "ぺん",
      "m": "ぽん",
      ",": "ぷん",
      ".": "ぴん",
      "/": "ぱん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["q"], {
      "9": "ゐ",
      "y": "ヶ",
      "u": "ょ",
      "i": "ゅ",
      "o": "ゃ",
      "p": "ゎ",
      "h": "ぇ",
      "j": "ぉ",
      "k": "ぅ",
      "l": "ぃ",
      ";": "ぁ",
      "n": "ゑ",
      ",": "、",
      ".": "。",
      "/": "ヵ",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["w"], {
      "0": "ぐゎ",
      "7": "ぐぉ",
      "9": "ぐぃ",
      "y": "ぐぇ",
      "u": "ぎょ",
      "i": "ぎゅ",
      "o": "ぎゃ",
      "[": "ぐぁ",
      "h": "げ",
      "j": "ご",
      "k": "ぐ",
      "l": "ぎ",
      ";": "が",
      "n": "げん",
      "m": "ごん",
      ",": "ぐん",
      ".": "ぎん",
      "/": "がん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["e"], {
      "9": "ずぃ",
      "y": "じぇ",
      "u": "じょ",
      "i": "じゅ",
      "o": "じゃ",
      "h": "ぜ",
      "j": "ぞ",
      "k": "ず",
      "l": "じ",
      ";": "ざ",
      "n": "ぜん",
      "m": "ぞん",
      ",": "ずん",
      ".": "じん",
      "/": "ざん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["r"], {
      "8": "どぅ",
      "9": "でぃ",
      "e": "です",
      "y": "ぢぇ",
      "u": "ぢょ",
      "i": "でゅ",
      "o": "ぢゃ",
      "h": "で",
      "j": "ど",
      "k": "づ",
      "l": "ぢ",
      ";": "だ",
      "n": "でん",
      "m": "どん",
      ",": "づん",
      ".": "ぢん",
      "/": "だん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["t"], {
      "7": "ヴォ",
      "8": "ヴ",
      "9": "ヴィ",
      "y": "ヴェ",
      "u": "びょ",
      "i": "びゅ",
      "o": "びゃ",
      "p": "ヴァ",
      "h": "べ",
      "j": "ぼ",
      "k": "ぶ",
      "l": "び",
      ";": "ば",
      "n": "べん",
      "m": "ぼん",
      ",": "ぶん",
      ".": "びん",
      "/": "ばん",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["l", ";"], {
      "w": "がい",
      "e": "ざい",
      "r": "だい",
      "t": "ばい",
      "a": "ない",
      "s": "かい",
      "d": "さい",
      "f": "たい",
      "g": "はい",
      "x": "らい",
      "c": "まい",
      "b": "ぱい",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["l"], {
      "k": "うう",
      ";": "あい",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["k", "l"], {
      "w": "ぐう",
      "e": "ずう",
      "r": "づう",
      "t": "ぶう",
      "a": "ぬう",
      "s": "くう",
      "d": "すう",
      "f": "つう",
      "g": "ふう",
      "x": "るう",
      "c": "むう",
      "b": "ぷう",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["j", "k"], {
      "w": "ごう",
      "e": "ぞう",
      "r": "どう",
      "t": "ぼう",
      "a": "のう",
      "s": "こう",
      "d": "そう",
      "f": "とう",
      "g": "ほう",
      "x": "ろう",
      "c": "もう",
      "b": "ぽう",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["j"], {
      "h": "えい",
      "k": "おう",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["h", "j"], {
      "w": "げい",
      "e": "ぜい",
      "r": "でい",
      "t": "べい",
      "a": "ねい",
      "s": "けい",
      "d": "せい",
      "f": "てい",
      "g": "へい",
      "x": "れい",
      "c": "めい",
      "b": "ぺい",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace([".", "/"], {
      "w": "ぎい",
      "e": "じい",
      "r": "ぢい",
      "t": "びい",
      "a": "にい",
      "s": "きい",
      "d": "しい",
      "f": "ちい",
      "g": "ひい",
      "x": "りい",
      "c": "みい",
      "b": "ぴい",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace([",", "."], {
      "w": "ぐい",
      "e": "ずい",
      "r": "づい",
      "t": "ぶい",
      "a": "ぬい",
      "s": "くい",
      "d": "すい",
      "f": "つい",
      "g": "ふい",
      "x": "るい",
      "c": "むい",
      "b": "ぷい",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["."], {
      ",": "うい",
      "/": "いい",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["o"], {
      "i": "ゆう",
      "p": "やい",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["i", "o"], {
      "w": "ぎゅう",
      "e": "じゅう",
      "r": "でゅう",
      "t": "びゅう",
      "a": "にゅう",
      "s": "きゅう",
      "d": "しゅう",
      "f": "ちゅう",
      "g": "ひゅう",
      "x": "りゅう",
      "c": "みゅう",
      "b": "ぴゅう",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["u", "i"], {
      "w": "ぎょう",
      "e": "じょう",
      "r": "ぢょう",
      "t": "びょう",
      "a": "にょう",
      "s": "きょう",
      "d": "しょう",
      "f": "ちょう",
      "g": "ひょう",
      "x": "りょう",
      "c": "みょう",
      "b": "ぴょう",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["i"], {
      "u": "よう",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["o", "p"], {
      "w": "ぎゃい",
      "e": "じゃい",
      "r": "ぢゃい",
      "t": "ゔぁい",
      "a": "にゃい",
      "s": "きゃい",
      "d": "しゃい",
      "f": "ちゃい",
      "g": "ふぁい",
      "x": "りゃい",
      "c": "みゃい",
      "b": "ぴゃい",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),
  sourceFace(["y", "u"], {
      "w": "ぐぇい",
      "e": "じぇい",
      "r": "ぢぇい",
      "t": "ヴぇい",
      "s": "くぇい",
      "d": "しぇい",
      "f": "ちぇい",
      "g": "ふぇい",
    }, { inputRole: 'composition', triggerPersistence: 'single' }),

];

export const KAWASEMI_KAI_FACES: Face[] = selectShortestFaces(KAWASEMI_KAI_SOURCES);

export const KAWASEMI_KAI: Layout = fromFaces('kawasemi-kai', 'かわせみ配列改', KAWASEMI_KAI_FACES);
